from typing import TYPE_CHECKING
from .Options import GlyphsOptions
from .Types import ButtonData, ButtonColor
from enum import IntEnum
from copy import deepcopy

options: GlyphsOptions

if TYPE_CHECKING:
    from . import GlyphsWorld

def randomize_colors(world: "GlyphsWorld", percentage: int = 0) -> None:
    buttons_to_randomize = []
    world.buttons = {
        name: deepcopy(button)
        for name, button in glyphs_buttons.items()
    }
    count = len(glyphs_buttons) * percentage / 100
    tmp = glyphs_buttons.copy()
    for _ in range(int(count)):
        key = world.random.choice(list(tmp.keys()))
        buttons_to_randomize.append(key)
        del tmp[key]
    
    for button in buttons_to_randomize:
        world.buttons[button].color = world.buttons[button].validColors[world.random.randint(0, len(world.buttons[button].validColors) - 1)]
        for _ in range(5): # Attempt to re-randomize any buttons that would force too much early progression
            if button.startswith("R1") and (world.buttons[button].color == ButtonColor.GREEN or world.buttons[button].color == ButtonColor.YELLOW):
                world.buttons[button].color = world.buttons[button].validColors[world.random.randint(0, len(world.buttons[button].validColors) - 1)]
            if button.startswith("R2") and not button.startswith("R2K") and world.buttons[button].color == ButtonColor.YELLOW:
                world.buttons[button].color = world.buttons[button].validColors[world.random.randint(0, len(world.buttons[button].validColors) - 1)]


def get_button_color(world: "GlyphsWorld", button: str) -> ButtonColor:
    return world.buttons[button].color

def get_raw_button_data(world: "GlyphsWorld") -> dict[int, int]:
    button_data: dict[int, int] = {}
    for _, button in world.buttons.items():
        button_data[button.id] = button.color.value
    return button_data

def get_button_spoiler_data(world: "GlyphsWorld") -> dict[str, str]:
    button_data: dict[int, int] = {}
    for key, value in world.buttons.items():
        button_data[key] = value.color.name
    return button_data

glyphs_buttons = {
    "R1A Save":                 ButtonData(0,   ButtonColor.RED,    validColors=[ButtonColor.RED]),
    "R1B Lowest":               ButtonData(1,   ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R1B 2nd Lowest":           ButtonData(2,   ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R1B 3rd Lowest":           ButtonData(3,   ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R1B 4th Lowest":           ButtonData(4,   ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R1B 5th Lowest":           ButtonData(5,   ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R1B 6th Lowest":           ButtonData(6,   ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R1B 7th Lowest":           ButtonData(7,   ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R1B Map Room":             ButtonData(8,   ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R1B Upper Puzzle":         ButtonData(9,   ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R1B Lower Puzzle":         ButtonData(10,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R1B Save":                 ButtonData(11,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R1C First":                ButtonData(12,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R1C Second":               ButtonData(13,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R1E Save":                 ButtonData(14,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R1F Right":                ButtonData(15,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2A Gate Left":            ButtonData(16,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2A Gate Right":           ButtonData(17,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2A Left Save":            ButtonData(18,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2A Right Save":           ButtonData(19,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2A Upper":                ButtonData(20,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2B Puzzle":               ButtonData(21,  ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "R2B Gate Left":            ButtonData(22,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2B Left Save":            ButtonData(23,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2B Right Save":           ButtonData(24,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2D Save":                 ButtonData(25,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2E Lower Save":           ButtonData(26,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2E Upper Save":           ButtonData(27,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2E Lower":                ButtonData(28,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2E Upper":                ButtonData(29,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2E Upper Puzzle":         ButtonData(30,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.GREEN]),
    "R2E Serpent Lock 1":       ButtonData(31,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2F Save":                 ButtonData(32,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2G Lower":                ButtonData(33,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.GREEN]),
    "R2G Middle":               ButtonData(34,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2G Moving Platform":      ButtonData(35,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2G Upper Left":           ButtonData(36,  ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "R2G Upper Middle":         ButtonData(37,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2G Upper Right":          ButtonData(38,  ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "R2G Hidden":               ButtonData(39,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2H Save":                 ButtonData(40,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2H Lower":                ButtonData(41,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2H Serpent Lock 2":       ButtonData(42,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2I Lower Left":           ButtonData(43,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2I Lower Middle":         ButtonData(44,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2I Upper Left":           ButtonData(45,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2I Upper Middle":         ButtonData(46,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2I Right":                ButtonData(47,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2I Save":                 ButtonData(48,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2J Gate Left":            ButtonData(49,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2J Save":                 ButtonData(50,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2K Chase 1":              ButtonData(51,  ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2K Chase 2":              ButtonData(52,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chase 3":              ButtonData(53,  ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chase 4":              ButtonData(54,  ButtonColor.GREEN,  validColors=[ButtonColor.GREEN, ButtonColor.PINK]),
    "R2K Chase 5":              ButtonData(55,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2K Chase 6":              ButtonData(56,  ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2K Chase Hidden":         ButtonData(57,  ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2K Chaos Upper 1":        ButtonData(58,  ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chaos Upper 2":        ButtonData(59,  ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chaos Upper 3":        ButtonData(60,  ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chaos Upper 4":        ButtonData(61,  ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chaos Middle 1":       ButtonData(62,  ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Middle 2":       ButtonData(63,  ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chaos Middle 3":       ButtonData(64,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Middle 4":       ButtonData(65,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chaos Middle 5":       ButtonData(66,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chaos Lower 1":        ButtonData(67,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Lower 2":        ButtonData(68,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Lower 3":        ButtonData(69,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Lower 4":        ButtonData(70,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Lower 5":        ButtonData(71,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Lower 6":        ButtonData(72,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Pivot 1":        ButtonData(73,  ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Pivot 2":        ButtonData(74,  ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK, ButtonColor.BLACK]),
    "R2K Chaos Sliding Platform": ButtonData(1075, ButtonColor.RED, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2K Chaos Gate Left":      ButtonData(75,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2L Right":                ButtonData(76,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2L Save":                 ButtonData(77,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2L Decent Upper Left":    ButtonData(78,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2L Decent Upper Right":   ButtonData(79,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.GREEN]),
    "R2L Decent Upper Middle":  ButtonData(80,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.GREEN]),
    "R2L Decent Middle":        ButtonData(81,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2L Decent Lower":         ButtonData(82,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.GREEN]),
    "R2M Save":                 ButtonData(83,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2M Water":                ButtonData(84,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2M Serpent Lock 3":       ButtonData(85,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2N Save":                 ButtonData(86,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2N Chase 1":              ButtonData(87,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2N Chase 2":              ButtonData(88,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2P Left":                 ButtonData(89,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R2P Puzzle":               ButtonData(90,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R2P Save":                 ButtonData(91,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R2Q Save":                 ButtonData(92,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3A Mirror Green":         ButtonData(93,  ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "R3A Mirror Blue":          ButtonData(94,  ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3A Left":                 ButtonData(95,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3A Middle Upper":         ButtonData(96,  ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3A Middle Lower":         ButtonData(97,  ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3A Save":                 ButtonData(98,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3B Save":                 ButtonData(99,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3C Left":                 ButtonData(100,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3C Middle":               ButtonData(101,  ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3C Right":                ButtonData(102, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3C Gate Right":           ButtonData(103,  ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3C Save":                 ButtonData(104, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3D Upper":                ButtonData(105, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3D Lower":                ButtonData(106, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3D Gate Upper":           ButtonData(107, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3D Save":                 ButtonData(108, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3E Upper":                ButtonData(109, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R3E Puzzle":               ButtonData(110, ButtonColor.BLACK,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3E QR Upper Left":        ButtonData(111, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3E QR Upper Right":       ButtonData(112, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3E QR Lower Left":        ButtonData(113, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3E QR Lower Right":       ButtonData(114, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3E Lower Room 1":         ButtonData(115, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3E Lower Room 2":         ButtonData(116, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R3E Lower Room 3":         ButtonData(117, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R3E Gate Upper":           ButtonData(118, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3E Save":                 ButtonData(119, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3F Right":                ButtonData(120, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3F Save":                 ButtonData(121, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3G Left":                 ButtonData(122, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3G Right":                ButtonData(123, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3G Save":                 ButtonData(124, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3H Left":                 ButtonData(125, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R3H Middle":               ButtonData(126, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3H Right":                ButtonData(127, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3H Gate Left":            ButtonData(128, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R3H Save":                 ButtonData(129, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R3I Challenge 1":          ButtonData(130, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3I Challenge 2":          ButtonData(131, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3I Challenge 3":          ButtonData(132, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3I Challenge 4":          ButtonData(133, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R3I Save":                 ButtonData(134, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R4A Left":                 ButtonData(135, ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "R4A Middle":               ButtonData(136, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4A Right":                ButtonData(137, ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R4B Save":                 ButtonData(138, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R4C 1st":                  ButtonData(139, ButtonColor.PINK,   validColors=[ButtonColor.GREEN, ButtonColor.PINK]),
    "R4C 2nd":                  ButtonData(140, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4C 3rd":                  ButtonData(141, ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R4C 4th":                  ButtonData(142, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4C 5th":                  ButtonData(143, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4C 6th":                  ButtonData(144, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4C 7th":                  ButtonData(145, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R4C 8th":                  ButtonData(146, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4C 9th":                  ButtonData(147, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4C 10th":                 ButtonData(148, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4C 5 Parry 1":            ButtonData(149, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4C 5 Parry 2":            ButtonData(150, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4C 5 Parry 3":            ButtonData(151, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4C 5 Parry 4":            ButtonData(152, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4C 5 Parry 5":            ButtonData(153, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4C Gate Right":           ButtonData(154, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4D Platforming 1st":      ButtonData(155, ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "R4D Platforming 2nd":      ButtonData(156, ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "R4D Platforming 3rd":      ButtonData(157, ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "R4D Platforming 4th":      ButtonData(158, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R4D Platforming 5th":      ButtonData(159, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R4D Multiparry":           ButtonData(160, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4D Ultra-Multiparry":     ButtonData(161, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4D Main Route 1st":       ButtonData(162, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4D Main Route 2nd":       ButtonData(163, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4D Main Route 3rd":       ButtonData(164, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4D Main Route 4th":       ButtonData(165, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4D Main Route 5th":       ButtonData(166, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R4D Main Route 6th":       ButtonData(167, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R4D Main Route 7th":       ButtonData(168, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4D Save":                 ButtonData(169, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R4E Save":                 ButtonData(170, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R4F Lower":                ButtonData(171, ButtonColor.GREEN,  validColors=[ButtonColor.GREEN, ButtonColor.PINK]),
    "R4F Save":                 ButtonData(172, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R4G 1st":                  ButtonData(173, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4G 2nd":                  ButtonData(174, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4G 3rd":                  ButtonData(175, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4G 4th":                  ButtonData(176, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4G 5th":                  ButtonData(177, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4G 6th":                  ButtonData(178, ButtonColor.PINK,   validColors=[ButtonColor.PINK]),
    "R4H Middle":               ButtonData(179, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "R4H Save":                 ButtonData(180, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R4I Left":                 ButtonData(181, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R4I Right":                ButtonData(182, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "R4I Gate Upper":           ButtonData(183, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R4I Save":                 ButtonData(184, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "R4J Save":                 ButtonData(185, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.BLACK]),
    "Dark 1":                   ButtonData(186, ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "Dark 2":                   ButtonData(187, ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "Dark 3":                   ButtonData(188, ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Dark 4":                   ButtonData(189, ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Dark 5":                   ButtonData(190, ButtonColor.GREEN,  validColors=[ButtonColor.GREEN]),
    "Dark 6":                   ButtonData(191, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Dark Save":                ButtonData(192, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Smile Refund":             ButtonData(193, ButtonColor.RED,    validColors=[ButtonColor.RED]),
    "Smile Hidden":             ButtonData(1194, ButtonColor.GREEN, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Collapse George Rescue":   ButtonData(194, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Void Chase 1":             ButtonData(195, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Void Chase 2":             ButtonData(196, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Void Chase 3":             ButtonData(197, ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Void Chase 4":             ButtonData(198, ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Void Chase Gate":          ButtonData(199, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Epilouge 1":               ButtonData(200, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between Save":             ButtonData(1201, ButtonColor.RED,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between Gate Left":        ButtonData(1202, ButtonColor.RED,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm1":              ButtonData(201, ButtonColor.GREEN,  validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm4":              ButtonData(202, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm5":              ButtonData(203, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm10":             ButtonData(204, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm13":             ButtonData(205, ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm19":             ButtonData(206, ButtonColor.YELLOW, validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm28":             ButtonData(207, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "Between rm30":             ButtonData(208, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "Between rm39":             ButtonData(209, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm40":             ButtonData(210, ButtonColor.PINK,   validColors=[ButtonColor.GREEN, ButtonColor.PINK]),
    "Between rm42 Button 1":    ButtonData(1211, ButtonColor.RED,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm42 Button 2":    ButtonData(1212, ButtonColor.RED,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm42 Button 3":    ButtonData(1213, ButtonColor.RED,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm42 Button 4":    ButtonData(1214, ButtonColor.RED,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm42 Button 5":    ButtonData(1215, ButtonColor.RED,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm42 Button 6":    ButtonData(1216, ButtonColor.RED,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm42 Button 7":    ButtonData(1217, ButtonColor.RED,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm43 Button 1":    ButtonData(211, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "Between rm43 Button 2":    ButtonData(212, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "Between rm57":             ButtonData(213, ButtonColor.PINK,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW, ButtonColor.PINK]),
    "Between rm66":             ButtonData(214, ButtonColor.BLUE,   validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between rm71":             ButtonData(215, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
    "Between Pre-Boss 1":       ButtonData(216, ButtonColor.RED,    validColors=[ButtonColor.RED, ButtonColor.BLUE, ButtonColor.GREEN, ButtonColor.YELLOW]),
}